" Plugins 
set rtp+=~/.vim/bundle/Vundle.vim           " add Vundle to runtime path 

call vundle#begin()                         
    Plugin 'VundleVim/Vundle.vim'                    
    " Git
    Plugin 'tpope/vim-fugitive'
    Plugin 'airblade/vim-gitgutter'
    " Editing 
    " Plugin 'tpope/vim-commentary'
    Plugin 'dense-analysis/ale'
    " Visual 
    " Plugin 'Yggdroot/indentLine'
    " Other
    Plugin 'nicwest/vim-http'
    Plugin 'ctrlpvim/ctrlp.vim'
    Plugin 'lervag/vimtex'
    Plugin 'mileszs/ack.vim'
    " Plugin 'syntastic'
call vundle#end()            

" CtrlP
let g:ctrlp_map = '<C-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_show_hidden=1

inoremap jj <esc>
let mapleader= ' '

" colours
colorscheme challenger_deep

" Search
set hlsearch                                    " highlight search terms
set incsearch                                   " highlight with each key stroke 
nnoremap <cr> :nohlsearch <cr>

" Spell
set dictionary+=/usr/share/dict/cracklib-small
set spellfile=~/.vim/spell/en.utf-8.add
setloca spell spelllang=en_gb
set nospell

" Buffer Switching
map <leader>nn :bNext <cr>
map <leader>bb :bprevious <cr>
nnoremap <C-c> :bp\|bd # <cr>


" Syntax 
syntax enable                                   " enable syntax processing

" Tabs & Spaces
set tabstop=4                                   " number of visual spaces per TAB
set softtabstop=4                               " number of spaces in tab when editing
set expandtab                                   " tabs are spaces
set shiftwidth=4

" Visual 
set relativenumber                             " :set rnu! == toggle relative number
set number
set showcmd
set wildmenu                                    " visual autocomplete for command menu
filetype indent on                              " load filetype-specific indent files
set lazyredraw                                  " redraw only when we need to
set showmatch                                   " highlight matching [{()}]
set cursorline
set laststatus=2
set updatetime=250 " set update time in milliseconds. git-gutter redraws signs based on this time

" Git-Fugative 
nnoremap <leader>gb :Git blame <cr>
nnoremap <leader>gp :Git push <cr>
nnoremap <leader>ga :Git add % <cr>
nnoremap <leader>gs :Git <cr>
nnoremap <leader>gcc :Git commit <cr>
nnoremap <leader>gbb :Git branch <cr>
nnoremap <leader>gd :Git diff <cr>
nnoremap <leader>gm :Git mergetool <cr>
nnoremap <leader>gcb :Git checkout  
nnoremap <leader>gnb :Git checkout -b 

" Folding 
set foldenable                                  " enable folding
set foldlevelstart=10                           " open most folds by default
set foldnestmax=10                              " 10 nested fold max
nnoremap ff za
set foldmethod=indent                           " fold based on indent level

" Work space
set splitbelow splitright
noremap <silent> <C-S-h> :vertical resize -3 <cr>
noremap <silent> <C-S-l> :vertical resize +3 <cr>
noremap <silent> <C-S-j> :resize -3 <cr>
noremap <silent> <C-S-k> :resize +3 <cr>
map <leader>tt :terminal <cr>
map <leader>ss :vs <cr>
map <leader>hs :split <cr>
map <leader>qq :quit <cr>

" Vimtex
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_latexmk = {
                        \ 'backend' : 'jobs',
                        \ 'background' : 1,
                        \ 'build_dir' : 'build',
                        \ 'callback' : 1,
                        \ 'continuous' : 1,
                        \ 'executable' : 'latexmk',
                        \ 'options' : [
                        \   '-verbose',
                        \   '-file-line-error',
                        \   '-synctex=1',
                        \   '-interaction=nonstopmode',
                        \  ],
                        \ }


